name: Metrics
on:
  # Run every day
  schedule: [{cron: "0 0 */1 * *"}]
  # Run manually and on each push
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    if: "github.repository == 'SevJSix/SevJSix'"
    steps:  
      - name: "Generate Metrics SVG"
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          plugin_languages: yes
          plugin_contributors: yes
          plugin_contributors_head: master
          plugin_contributors_ignored: github-actions[bot], dependabot[bot]
          plugin_lines: yes
          plugin_traffic: yes
          plugin_languages_colors: github
          plugin_languages_ignored:                        # List of languages to ignore
          plugin_languages_details: bytes-size, percentage             # Additionally display total bytes size and percentage
          plugin_languages_threshold: 2%                               # Hides all languages less than 2%
          plugin_languages_limit: 8                                    # Display up to 8 languages
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year # Display half year instead of full year
          
          
          
